% function [mass_sumsum_H,mass_sumsum_He,mass_sumsum_O,mass_sumsum_O2]=static_c6_mass_ratio(data_static_c6_2)
%%
time_unix          =data_static_c6_2{4};
bkg                =data_static_c6_2{24};
% dead               =data_static_c6_2{25};
data               =data_static_c6_2{26};
eflux              =data_static_c6_2{27};
% eflux_energy_labl_32=data_static_c6_2{74};
% eflux_energy_labl_64=data_static_c6_2{78};
% compno             =data_static_c6_2{67};
% nswp               =data_static_c6_2{42};
% magf_labl          =data_static_c6_2{68};
att_ind            =data_static_c6_2{17};
% num_dists          =data_static_c6_2{35};
swp_ind            =data_static_c6_2{14};
% nmlut              =data_static_c6_2{44};
mass_arr           =data_static_c6_2{55};
energy             =data_static_c6_2{46};
% denergy            =data_static_c6_2{47};
% time_delta         =data_static_c6_2{7};
% geom_factor        =data_static_c6_2{58};
% time_integ         =data_static_c6_2{8};
% ndef               =data_static_c6_2{39};
% nenergy            =data_static_c6_2{36};
theta              =data_static_c6_2{48};
dtheta             =data_static_c6_2{49};
phi                =data_static_c6_2{50};
dphi               =data_static_c6_2{51};
% gf                 =data_static_c6_2{53};
data_re            =data-bkg;
unix_dayoffset_static     =datenum('19700101','yyyymmdd');
tlist_static              =time_unix/86400+unix_dayoffset_static;
time_dur                  =length(tlist_static);

mass_sumsum_O              =zeros(1,time_dur);
mass_sumsum_O2             =zeros(1,time_dur);
mass_sumsum_H              =zeros(1,time_dur);
mass_sumsum_He             =zeros(1,time_dur);
n                        =0;
m_p                      =1.6726e-27; % kg
eV                       =1.602e-19;
kB                       =1.38e-23;
m_H                      =1*m_p;
m_He                     =4*m_p;
m_O                      =16*m_p;
m_O2                     =32*m_p;
%%
for i_2=1:time_dur
    mass_sum_O           =0;
    mass_sum_O2          =0;
    mass_sum_H           =0;
    mass_sum_He          =0;
    att_ind_i            =att_ind(i_2)+1;
    swp_ind_2_i          =swp_ind(i_2)+1;
    mass_arr_2_i         =permute(mass_arr(:,swp_ind_2_i,:),[3 1 2]);
    energy_2_i           =permute(energy(:,swp_ind_2_i,:),[3 1 2]);
    theta_2_i            =permute(theta(:,swp_i.nd_2_i,:),[3 1 2]);
    dtheta_2_i           =permute(dtheta(:,swp_ind_2_i,:),[3 1 2]);
    phi_2_i              =permute(phi(:,swp_ind_2_i,:),[3 1 2]);
    dphi_2_i             =permute(dphi(:,swp_ind_2_i,:),[3 1 2]);
    denergy_2_i          =permute(energy(:,swp_ind_2_i,:),[3 1 2]);
    for j_2=1:32
        mass_H               =find(mass_arr_2_i(:,j_2)<1.8&mass_arr_2_i(:,j_2)>0.3);
        mass_He              =find(mass_arr_2_i(:,j_2)<2.5&mass_arr_2_i(:,j_2)>1.8);
        mass_O               =find(mass_arr_2_i(:,j_2)<26&mass_arr_2_i(:,j_2)>6);
        mass_O2              =find(mass_arr_2_i(:,j_2)<66&mass_arr_2_i(:,j_2)>26);
        v_H                  =sqrt(2.*energy_2_i(mass_H,j_2).*10.^4.*eV./m_H);
        v_He                 =sqrt(2.*energy_2_i(mass_He,j_2).*10.^4.*eV./m_He);
        v_O                  =sqrt(2.*energy_2_i(mass_O,j_2).*10.^4.*eV./m_O);
        v_O2                 =sqrt(2.*energy_2_i(mass_O2,j_2).*10.^4.*eV./m_O2);
        n_H                  =pi/180*2*dphi_2_i(mass_H,j_2).*sin(dtheta_2_i(mass_H,j_2)/2*pi/180).*(eflux(mass_H,j_2,i_2).*denergy_2_i(mass_H,j_2)./(energy_2_i(mass_H,j_2).*v_H));
        n_He                 =pi/180*2*dphi_2_i(mass_He,j_2).*sin(dtheta_2_i(mass_He,j_2)/2*pi/180).*(eflux(mass_He,j_2,i_2).*denergy_2_i(mass_He,j_2)./(energy_2_i(mass_He,j_2).*v_He));
        n_O                  =pi/180*221*dphi_2_i(mass_O,j_2).*sin(dtheta_2_i(mass_O,j_2)/2*pi/180).*(eflux(mass_O,j_2,i_2).*denergy_2_i(mass_O,j_2)./(energy_2_i(mass_O,j_2).*v_O));
        n_O2                 =pi/180*2*dphi_2_i(mass_O2,j_2).*sin(dtheta_2_i(mass_O2,j_2)/2*pi/180).*(eflux(mass_O2,j_2,i_2).*denergy_2_i(mass_O2,j_2)./(energy_2_i(mass_O2,j_2).*v_O2));
        mass_sum_H           =mass_sum_H+sum(n_H);
        mass_sum_He          =mass_sum_He+sum(n_He);
        mass_sum_O           =mass_sum_O+sum(n_O);
        mass_sum_O2          =mass_sum_O2+sum(n_O2);
        %     mass_counts_O          =data06(mass_O06,j06_2,i06_2)-bkg06(mass_O06,j06_2,i06_2);
        %     mass_counts_O2         =data06(mass_O2_06,j06_2,i06_2)-bkg06(mass_O2_06,j06_2,i06_2);
        %     mass_counts_H          =data06(mass_H06,j06_2,i06_2)-bkg06(mass_H06,j06_2,i06_2);
        %     mass_counts_He         =data06(mass_He06,j06_2,i06_2)-bkg06(mass_He06,j06_2,i06_2);
        %     mass_sum_O             =mass_sum_O+mass_counts_O;
        %     mass_sum_O2            =mass_sum_O2+mass_counts_O2;
        %     mass_sum_H             =mass_sum_H+mass_counts_H;
        %     mass_sum_He            =mass_sum_He+mass_counts_He;
    end
    n                        =n+1;
    mass_sumsum_O(1,n)       =mass_sum_O;
    mass_sumsum_O2(1,n)      =mass_sum_O2;
    mass_sumsum_H(1,n)       =mass_sum_H;
    mass_sumsum_He(1,n)      =mass_sum_He;
end